<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13375" started-at="2022-01-23T22:33:16 IST" finished-at="2022-01-23T22:33:29 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13375" started-at="2022-01-23T22:33:16 IST" finished-at="2022-01-23T22:33:29 IST">
      <class name="practise.TestForListener">
        <test-method status="PASS" signature="connectDatabase()[pri:0, instance:practise.TestForListener@25af5db5]" name="connectDatabase" is-config="true" duration-ms="6" started-at="2022-01-23T22:33:16 IST" finished-at="2022-01-23T22:33:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- connectDatabase -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:practise.TestForListener@25af5db5]" name="launchBrowser" is-config="true" duration-ms="4772" started-at="2022-01-23T22:33:16 IST" finished-at="2022-01-23T22:33:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="configBM()[pri:0, instance:practise.TestForListener@25af5db5]" name="configBM" is-config="true" duration-ms="2557" started-at="2022-01-23T22:33:20 IST" finished-at="2022-01-23T22:33:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method status="FAIL" signature="contactTest()[pri:0, instance:practise.TestForListener@25af5db5]" name="contactTest" duration-ms="3952" started-at="2022-01-23T22:33:23 IST" finished-at="2022-01-23T22:33:27 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [B] but found [A]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [B] but found [A]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at practise.TestForListener.contactTest(TestForListener.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactTest -->
        <test-method status="PASS" signature="configAM()[pri:0, instance:practise.TestForListener@25af5db5]" name="configAM" is-config="true" duration-ms="1222" started-at="2022-01-23T22:33:27 IST" finished-at="2022-01-23T22:33:28 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method status="PASS" signature="configAC()[pri:0, instance:practise.TestForListener@25af5db5]" name="configAC" is-config="true" duration-ms="654" started-at="2022-01-23T22:33:28 IST" finished-at="2022-01-23T22:33:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAC -->
        <test-method status="PASS" signature="disconnectDatabase()[pri:0, instance:practise.TestForListener@25af5db5]" name="disconnectDatabase" is-config="true" duration-ms="1" started-at="2022-01-23T22:33:29 IST" finished-at="2022-01-23T22:33:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- disconnectDatabase -->
      </class> <!-- practise.TestForListener -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
